### ISSUE TITLE
Don't implement RSA yourself.

### ISSUE THREAD

**Issue by maqp** [Caipo/Tinfoil-Chat#2]
Among other things, you're not checking RSA prime distance making this toy implementation vulnerable to Fermat's method.

Always use a proper library like https://github.com/pyca/cryptography

RSA is not ideal in any case given that it lacks forward secrecy, so my advice is to use x25519 or x448 for ephemeral key exchanges, and ed25519 or ed448 for signatures.

EDIT: The readme actually has some decent warnings about not using the SW in production, so I guess this ticket does not matter.

**Comment by Caipo** [comment]
Thanks I added your suggestions to the read me. If I decide to every dust this project ill try and clean up the vulnerability
